# Generated by Django 3.0.4 on 2020-03-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Media',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
