# Generated by Django 3.0.4 on 2020-03-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200325_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Media',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
