# Generated by Django 3.0.8 on 2020-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first',
            field=models.CharField(default='first', max_length=20),
        ),
    ]
