# Generated by Django 3.0.8 on 2020-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='first', max_length=30),
        ),
    ]
