# Generated by Django 3.0.8 on 2020-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200719_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first',
            field=models.CharField(default='first', max_length=30),
        ),
    ]
