# Generated by Django 3.1 on 2020-08-12 04:19

import core.utility
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('_file', models.FileField(blank=True, max_length=255, null=True, upload_to=core.utility.get_file_path)),
                ('tags', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, null=True)),
                ('last', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('PREMIUM', 'Premium'), ('FREE', 'Free')], default='FREE', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscriber')),
                ('voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.media')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='interested_topic',
            field=models.ManyToManyField(to='core.Topic'),
        ),
        migrations.AddField(
            model_name='media',
            name='topic',
            field=models.ForeignKey(blank=True, db_column='name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topic'),
        ),
    ]
