# Generated by Django 3.0.5 on 2020-04-09 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='nil', max_length=30, null=True)),
                ('Description', models.TextField(default='nil', null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='media/%y/%m/%d')),
                ('Tags', models.CharField(blank=True, default='nil', max_length=20, null=True)),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(default='nil', max_length=30, null=True)),
                ('Last', models.CharField(blank=True, default='nil', max_length=30, null=True)),
                ('Email', models.EmailField(default='example@egs.com', max_length=254)),
                ('Type', models.CharField(choices=[('PREMIUM', 'Premium'), ('FREE', 'Free')], default='FREE', max_length=30)),
                ('Interest', models.CharField(default='nil', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='nil', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Subscriber')),
                ('Voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='Topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Topic'),
        ),
    ]
