# Generated by Django 3.0.4 on 2020-05-04 08:42

import core.utility
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='File',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.utility.get_file_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='Tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='Topic',
            field=models.ForeignKey(blank=True, db_column='Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Topic'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='First',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='Interest',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='Interest',
            field=models.ManyToManyField(to='core.Topic'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='Last',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
