# Generated by Django 3.0.4 on 2020-04-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('discription', models.TextField(blank=True, null=True)),
                ('filename', models.FileField(upload_to='uploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Type', models.CharField(choices=[('PREMIUM', 'Premium'), ('FREE', 'Free')], max_length=30)),
                ('Interest', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Voted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.subscriber')),
                ('Voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.topic'),
        ),
    ]
